### ISSUE TITLE
Build issue during Lab 4 - Application Deployment with Red Hat OpenShift Container Platform 4

### ISSUE THREAD

**Issue by Brun0fl** [redhat-gpte-devopsautomation/openshift-tasks#2]
From Step 6 on several errors appear. I tried the <Lab 4> in "Application Deployment with Red Hat OpenShift Container Platform 4" 3 times and issue seems to persist. It appears after the step 2.2 where we run the build from Jenkins <click Build Run>.

oc logs -f bc/openshift-tasks
`
Cloning "https://github.com/redhat-gpte-devopsautomation/openshift-tasks" ...
	Commit:	308f21ff69fa357410b4b64db73b99877b115009 (Merge pull request #1 from jeichler/https)
	Author:	Wolfgang Kulhanek <wkulhanek@users.noreply.github.com>
	Date:	Tue Aug 20 03:01:58 2019 +0900
Caching blobs under "/var/cache/blobs".
Getting image source signatures
Copying blob sha256:2cb1196a3b2716c68f8ba88205548a9f659e98edc30898ca3a7c762b4d5e0190
Copying blob sha256:c9c433594a59dca1d747e916d5403e64705d217dac148804bcbcd712392141a8
Copying blob sha256:12cdc891015d1e9ef37f50557c7b7d9b280a5bd869d523b5fac1b9409d6dd9bd
Copying config sha256:237b03664fa50c9afaeaca3d941999637b56e89152da3111c33bac5459bf8467
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image image-registry.openshift-image-registry.svc:5000/openshift/jboss-eap71-openshift@sha256:db4b1cc088c91d39869c4bee4d6cfb1430310971a5e1ed3720a553b6f801db5b
STEP 1: FROM image-registry.openshift-image-registry.svc:5000/openshift/jboss-eap71-openshift@sha256:db4b1cc088c91d39869c4bee4d6cfb1430310971a5e1ed3720a553b6f801db5b
STEP 2: LABEL "io.openshift.build.commit.author"="Wolfgang Kulhanek <wkulhanek@users.noreply.github.com>" "io.openshift.build.commit.date"="Tue Aug 20 03:01:58 2019 +0900" "io.openshift.build.commit.id"="308f21ff69fa357410b4b64db73b99877b115009" "io.openshift.build.commit.ref"="master" "io.openshift.build.commit.message"="Merge pull request #1 from jeichler/https" "io.openshift.build.source-location"="https://github.com/redhat-gpte-devopsautomation/openshift-tasks" "io.openshift.build.image"="image-registry.openshift-image-registry.svc:5000/openshift/jboss-eap71-openshift@sha256:db4b1cc088c91d39869c4bee4d6cfb1430310971a5e1ed3720a553b6f801db5b"
STEP 3: ENV OPENSHIFT_BUILD_NAME="openshift-tasks-3" OPENSHIFT_BUILD_NAMESPACE="a7dc-tasks" OPENSHIFT_BUILD_SOURCE="https://github.com/redhat-gpte-devopsautomation/openshift-tasks" OPENSHIFT_BUILD_COMMIT="308f21ff69fa357410b4b64db73b99877b115009" MAVEN_MIRROR_URL="http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public"
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 185:0 /tmp/src
time="2019-09-19T16:28:51Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah087396128/mnt/rootfs\": error checking if \"/tmp/buildah087396128/mnt/rootfs/sys/fs/cgroup/freezer\" is mounted: no such file or directory"
time="2019-09-19T16:28:51Z" level=warning msg="pkg/bind: error unmounting \"/tmp/buildah087396128/mnt/rootfs\": error checking if \"/tmp/buildah087396128/mnt/rootfs/sys/fs/cgroup/freezer\" is mounted: no such file or directory"
STEP 7: USER 185
STEP 8: RUN /usr/local/s2i/assemble
INFO Performing Maven build in /tmp/src
INFO Using MAVEN_OPTS -Xms192m -Xmx768m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError
INFO Using Apache Maven 3.5.0 (Red Hat 3.5.0-4.3)
Maven home: /opt/rh/rh-maven35/root/usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.18.0-80.7.2.el8_0.x86_64", arch: "amd64", family: "unix"
INFO Running 'mvn -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga -Dfabric8.skip=true --batch-mode -Djava.net.preferIPv4Stack=true -s /home/jboss/.m2/settings.xml -Dmaven.repo.local=/tmp/artifacts/m2  package'
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Downloading: http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public/org/jboss/bom/jboss-eap-javaee7-with-tools/7.1.3.GA/jboss-eap-javaee7-with-tools-7.1.3.GA.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.3.GA from/to mirror.default (http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public): nexus.opentlc-shared.svc.cluster.local: Name or service not known @ line 70, column 19
[ERROR] 'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 82, column 17
[ERROR] 'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar is missing. @ line 89, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.resteasy:resteasy-jackson-provider:jar is missing. @ line 102, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.2_spec:jar is missing. @ line 109, column 17
[ERROR] 'dependencies.dependency.version' for junit:junit:jar is missing. @ line 116, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 122, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 128, column 17
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.3.GA from/to mirror.default (http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public): nexus.opentlc-shared.svc.cluster.local: Name or service not known @ line 70, column 19
[ERROR] 'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 82, column 17
[ERROR] 'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar is missing. @ line 89, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.resteasy:resteasy-jackson-provider:jar is missing. @ line 102, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.2_spec:jar is missing. @ line 109, column 17
[ERROR] 'dependencies.dependency.version' for junit:junit:jar is missing. @ line 116, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 122, column 17
[ERROR] 'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 128, column 17

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:382)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]   The project org.jboss.quickstarts.eap:tasks:1.0-0 (/tmp/src/pom.xml) has 8 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.3.GA from/to mirror.default (http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public): nexus.opentlc-shared.svc.cluster.local: Name or service not known @ line 70, column 19: Unknown host nexus.opentlc-shared.svc.cluster.local: Name or service not known -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.3.GA from/to mirror.default (http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public): nexus.opentlc-shared.svc.cluster.local: Name or service not known
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1245)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:457)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:423)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:580)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:372)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.3.GA from/to mirror.default (http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public): nexus.opentlc-shared.svc.cluster.local: Name or service not known
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:303)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:193)
	... 23 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss.bom:jboss-eap-javaee7-with-tools:pom:7.1.3.GA from/to mirror.default (http://nexus.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public): nexus.opentlc-shared.svc.cluster.local: Name or service not known
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:258)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:529)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
	... 27 more
Caused by: org.apache.maven.wagon.TransferFailedException: nexus.opentlc-shared.svc.cluster.local: Name or service not known
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:569)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:436)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
	... 32 more
Caused by: java.net.UnknownHostException: nexus.opentlc-shared.svc.cluster.local: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:113)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
	... 41 more
[ERROR]     'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 82, column 17
[ERROR]     'dependencies.dependency.version' for org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar is missing. @ line 89, column 17
[ERROR]     'dependencies.dependency.version' for org.jboss.resteasy:resteasy-jackson-provider:jar is missing. @ line 102, column 17
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.2_spec:jar is missing. @ line 109, column 17
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 116, column 17
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.junit:arquillian-junit-container:jar is missing. @ line 122, column 17
[ERROR]     'dependencies.dependency.version' for org.jboss.arquillian.protocol:arquillian-protocol-servlet:jar is missing. @ line 128, column 17
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/local/s2i/assemble": exit status 1`

**Comment by pavelanni** [comment]
Hi Bruno,
I've checked it in my environment and yes, the pipeline gives be the same error. I'm working on it.

**Comment by pavelanni** [comment]
Bruno:
In this command:
`oc set env bc openshift-tasks MAVEN_MIRROR_URL=http://nexus3.opentlc-shared.svc.cluster.local:8081/repository/maven-all-public`
it should be *nexus3*, not *nexus*. 
I'll update the labs.
Could you please test and confirm that it works for you? Thanks!

**Comment by Brun0fl** [comment]
Hi Pavel,
Thanks for the prompt reply.
Yes! it is working perfectly now, awesome! :)
Thanks
                                                                        Bruno Fonseca De Lima
                                                E-mail: brunofl@br.ibm.com
                        IS - Cloud Infrastructure
                        +55-51-995117649
                        ITIL V3 
                        Lean Six Sigma Black Belt trained                                                                                                
                        Let's have conversations that count                                                
 
 
 
 
 
 
----- Original message -----From: Pavel Anni <notifications@github.com>To: redhat-gpte-devopsautomation/openshift-tasks <openshift-tasks@noreply.github.com>Cc: Bruno de Lima <brunofl@br.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [redhat-gpte-devopsautomation/openshift-tasks] Build issue during Lab 4 - Application Deployment with Red Hat OpenShift Container Platform 4 (#2)Date: Thu, Sep 19, 2019 6:33 PM 
Bruno:In this command:oc set env bc openshift-tasks MAVEN_MIRROR_URL=http://nexus3.opentlc-shared.svc.cluster.local:8081/repository/maven-all-publicit should be nexus3, not nexus.I'll update the labs.Could you please test and confirm that it works for you? Thanks!
